### ISSUE TITLE
No Dropout for input layer ?

### ISSUE THREAD

**Issue by malharjajoo** [homaralex/mc-dropout-mnist#1]
In the LeNet model with dropout ( "[lenet_all](https://github.com/homaralex/mc-dropout-mnist/blob/master/models.py#L18)" in the mnist.py file), is there any reason for not applying dropout after the input layer ?

I have read the Experiments in [Bayesian Convnet paper](http://mlg.eng.cam.ac.uk/yarin/PDFs/NIPS_2015_bayesian_convnets.pdf) you referenced
and I can see that there is no mention about Dropout after input layer. However,

Quoting from the [MCDropout paper](https://arxiv.org/pdf/1506.02142.pdf), Section 3 says:

> We show that a neural network with arbitrary depth and
non-linearities, with dropout applied before every weight
layer, is mathematically equivalent

Another thing that I realized after reading some SO posts is that when inputs are pixels, this wouldn't be such 
a bad idea as you wouldn't lose that much information.

**Comment by alexrakowski** [comment]
I don't see why it wouldn't work, it is essentially adding noise to the inputs which has been often done in the image processing domain (although usually with gaussian and not bernoulli noise).

**Comment by malharjajoo** [comment]
Thanks for the reply, I raised this issue just to confirm if there was any reason you had chosen not to do so. 

Ill close it now.
