### ISSUE TITLE
Misleading function/architecture name ?

### ISSUE THREAD

**Issue by malharjajoo** [homaralex/mc-dropout-mnist#2]
Hi,

Looking at the functions in [this file](https://github.com/homaralex/mc-dropout-mnist/blob/master/models.py), their name involves "lenet" ... but when I looked at [LeNet paper](http://yann.lecun.com/exdb/publis/pdf/lecun-01a.pdf) and [various articles](https://engmrk.com/lenet-5-a-classic-cnn-architecture/), the **second convolutional layer** in Lenet-5 is mapped a little differently than in a simple CNN (like in your code) ... 

hence it might be good to rename the function or write a small comment ?

**Comment by alexrakowski** [comment]
Do you mean the number of filters?
As far as I remember I implemented it based on the `caffe` implementation from Yarin Gal's [repo](https://github.com/yaringal/DropoutUncertaintyCaffeModels/blob/master/mnist_uncertainty/lenet_all_dropout_deploy.prototxt) , hence the naming

**Comment by malharjajoo** [comment]
That is a minor difference, but I mean the second convolutional layer is mapped differently in case of a LeNet-5 architecture. Please have a look at the [article I mentioned above](https://engmrk.com/lenet-5-a-classic-cnn-architecture/) or even the original LeNet-5 paper.

**Comment by alexrakowski** [comment]
Could you specify precisely what the difference is?

**Comment by malharjajoo** [comment]
![image](https://user-images.githubusercontent.com/15148321/72380698-dc660f00-370d-11ea-9d5f-13d3fd1e9843.png)

**Comment by alexrakowski** [comment]
Ok, thanks for pointing this out - I have added a comment to the file.
As a sidenote - this would prove the effectiveness of the method even more, since the model I implemented should be even more prone to overfitting than the smaller one, right?
